export const CREATE_TASK = 'CREATE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const START_FETCH = 'START_FETCH';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const ERROR_CATCHED = 'ERROR_CATCHED';
export const INPUT_EDIT_LOGIN = 'INPUT_EDIT_LOGIN';
export const INPUT_EDIT_REGISTER = 'INPUT_EDIT_REGISTER';
export const TOGGLE_MODE = 'TOGGLE_MODE';
